#配置数据源
spring:
  datasource:
    url: jdbc:mysql://hadoop102:3306/gulimall_pms
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product

#配置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # 告诉mybatis-plus xml所在位置
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)  #这个是全局的配置 和 @TableLogic有同样的效果，但是肯定已粒度更小的@TableLogic为准。
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

#server
server:
  port: 10001
logging:
  level:
    com.atguigu.gulimall: debug   #日志的级别
#log.