#配置数据源
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_routh_1
          uri: https://www.baidu.com/
          predicates:
            #以下是断言条件，必选全部符合条件
            - Query=url,baidu
        - id: test_routh_2
          uri: https://www.qq.com/
          predicates:
            #以下是断言条件，必选全部符合条件
            - Query=url,qq
  application:
    name: gulimall-gateway

#server
server:
  port: 12001